name: Build and Deploy

on:
  push:
    branches:
      - '*'
      - parth-phase-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'maven'
          java-version: '3.8.2'

      - name: Build with Maven
        run: mvn -B package

      - name: Deploy to Production
        run: java -jar target/your-app.jar
